-- Lumina — initial schema (migration 0001)
--
-- Notes:
--  * All timestamps are stored as INTEGER Unix seconds (UTC) for cheap ordering.
--  * `photos.id` is a UUIDv4 string, generated by the backend on import.
--  * The schema is intentionally non-destructive: removing a photo from the
--    catalog only sets `deleted_at`; the physical file is never touched.
--  * FTS5 mirrors a denormalized text projection of each photo and is kept in
--    sync from application code (see `search` module) rather than triggers, so
--    tag edits can update it transactionally alongside the join table.

-- ---------------------------------------------------------------------------
-- Photos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS photos (
    id            TEXT    PRIMARY KEY NOT NULL,
    path          TEXT    NOT NULL UNIQUE,
    filename      TEXT    NOT NULL,
    folder        TEXT    NOT NULL,
    format        TEXT    NOT NULL,               -- jpeg | png | webp | heic | raw | ...
    media_type    TEXT    NOT NULL DEFAULT 'photo', -- photo | video (architecture only)

    -- Timestamps (Unix seconds, UTC)
    taken_at      INTEGER,                          -- from EXIF DateTimeOriginal
    file_created  INTEGER,
    file_modified INTEGER,
    imported_at   INTEGER NOT NULL,

    -- Geometry
    width         INTEGER NOT NULL DEFAULT 0,
    height        INTEGER NOT NULL DEFAULT 0,
    orientation   INTEGER NOT NULL DEFAULT 1,       -- EXIF orientation 1..8
    file_size     INTEGER NOT NULL DEFAULT 0,       -- bytes

    -- Camera / optics (EXIF)
    camera_make   TEXT,
    camera_model  TEXT,
    lens          TEXT,
    iso           INTEGER,
    focal_length  REAL,                             -- mm
    aperture      REAL,                             -- f-number
    shutter_speed TEXT,                             -- human-readable, e.g. "1/250"
    gps_lat       REAL,
    gps_lon       REAL,

    -- Integrity & catalog metadata
    hash          TEXT,                             -- sha256 of file bytes (dedupe/integrity)
    rating        INTEGER NOT NULL DEFAULT 0,       -- 0..5 stars
    color_label   TEXT,                             -- none|red|yellow|green|blue|purple
    is_favorite   INTEGER NOT NULL DEFAULT 0,       -- 0|1
    is_raw        INTEGER NOT NULL DEFAULT 0,       -- 0|1

    -- Thumbnail pipeline
    thumb_status  TEXT    NOT NULL DEFAULT 'pending', -- pending | ready | failed
    thumb_path    TEXT,                             -- absolute path to cached .webp

    deleted_at    INTEGER                           -- soft delete (catalog removal only)
);

CREATE INDEX IF NOT EXISTS idx_photos_taken_at   ON photos(taken_at DESC);
CREATE INDEX IF NOT EXISTS idx_photos_imported    ON photos(imported_at DESC);
CREATE INDEX IF NOT EXISTS idx_photos_folder      ON photos(folder);
CREATE INDEX IF NOT EXISTS idx_photos_rating      ON photos(rating);
CREATE INDEX IF NOT EXISTS idx_photos_favorite    ON photos(is_favorite);
CREATE INDEX IF NOT EXISTS idx_photos_raw         ON photos(is_raw);
CREATE INDEX IF NOT EXISTS idx_photos_media_type  ON photos(media_type);
CREATE INDEX IF NOT EXISTS idx_photos_thumb       ON photos(thumb_status);
CREATE INDEX IF NOT EXISTS idx_photos_hash        ON photos(hash);
CREATE INDEX IF NOT EXISTS idx_photos_deleted     ON photos(deleted_at);
-- Composite for the default library view: newest-first among live photos.
CREATE INDEX IF NOT EXISTS idx_photos_live_taken
    ON photos(deleted_at, taken_at DESC, imported_at DESC);

-- ---------------------------------------------------------------------------
-- Tags
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
    id         TEXT PRIMARY KEY NOT NULL,
    name       TEXT NOT NULL UNIQUE COLLATE NOCASE,
    color      TEXT,
    created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS photo_tags (
    photo_id TEXT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    tag_id   TEXT NOT NULL REFERENCES tags(id)   ON DELETE CASCADE,
    PRIMARY KEY (photo_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_photo_tags_tag ON photo_tags(tag_id);

-- ---------------------------------------------------------------------------
-- Albums (manual + smart)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS albums (
    id         TEXT PRIMARY KEY NOT NULL,
    name       TEXT NOT NULL,
    kind       TEXT NOT NULL DEFAULT 'manual',    -- manual | smart
    rule       TEXT,                              -- JSON smart-rule (NULL for manual)
    icon       TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS album_photos (
    album_id TEXT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
    photo_id TEXT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    added_at INTEGER NOT NULL,
    PRIMARY KEY (album_id, photo_id)
);
CREATE INDEX IF NOT EXISTS idx_album_photos_photo ON album_photos(photo_id);

-- ---------------------------------------------------------------------------
-- Watched folders (import roots monitored in real time)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS watched_folders (
    id       TEXT PRIMARY KEY NOT NULL,
    path     TEXT NOT NULL UNIQUE,
    added_at INTEGER NOT NULL,
    active   INTEGER NOT NULL DEFAULT 1
);

-- ---------------------------------------------------------------------------
-- Key/value settings (JSON values)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- AI artifacts (architecture only — populated by future AI providers)
-- ---------------------------------------------------------------------------
-- Generic embedding store so CLIP/face/OCR vectors can be added without a
-- schema migration. `kind` disambiguates the producer; `vector` is a raw
-- little-endian f32 blob; `dim` records its length.
CREATE TABLE IF NOT EXISTS ai_embeddings (
    id         TEXT PRIMARY KEY NOT NULL,
    photo_id   TEXT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    kind       TEXT NOT NULL,                     -- clip | face | ocr | ...
    model      TEXT NOT NULL,
    dim        INTEGER NOT NULL,
    vector     BLOB NOT NULL,
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_embeddings_photo ON ai_embeddings(photo_id);
CREATE INDEX IF NOT EXISTS idx_ai_embeddings_kind  ON ai_embeddings(kind);

-- Detected regions (faces, text boxes) — architecture only.
CREATE TABLE IF NOT EXISTS ai_regions (
    id         TEXT PRIMARY KEY NOT NULL,
    photo_id   TEXT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    kind       TEXT NOT NULL,                     -- face | text
    label      TEXT,
    confidence REAL,
    x REAL, y REAL, w REAL, h REAL,               -- normalized 0..1 bbox
    data       TEXT,                              -- JSON extra (e.g. OCR string)
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_regions_photo ON ai_regions(photo_id);

-- ---------------------------------------------------------------------------
-- Full-text search (FTS5). Content-less external index keyed by photo id.
-- ---------------------------------------------------------------------------
CREATE VIRTUAL TABLE IF NOT EXISTS photos_fts USING fts5 (
    photo_id UNINDEXED,
    filename,
    folder,
    camera,          -- "make model"
    lens,
    tags,            -- space-joined tag names
    color,
    tokenize = "unicode61 remove_diacritics 2"
);
